### ISSUE TITLE
Register as AppDelegate service for Godot

### ISSUE THREAD

**Issue by aogden** [rktprof/godot-ios-extensions#3]
Loving this modern approach to iOS extensions for Godot. I'm trying to create a package using this project with an SDK dependency (Facebook) that requires some AppDelegate [modifications](https://developers.facebook.com/docs/facebook-login/ios).
Do you have any ideas on how I could patch the AppDelegate that Godot generates or register as a AppDelegateService similar to how the [APNS plugin](https://github.com/godotengine/godot-ios-plugins/blob/master/plugins/apn/godot_apn_delegate.mm#L46) does it? It looks like the iOS plugins project has been abandoned and I would rather use an extension but I don't see a way to make these AppDelegate modifications/registrations through the SwiftGodot and GDExtensions currently.

**Comment by rktprof** [comment]
Hello! I'm not sure you can do that from a GDExtension, this project builds on the [SwiftGodot](https://github.com/migueldeicaza/SwiftGodot) extension and the creator of that can probably give a more definitive answer

**Comment by aogden** [comment]
Thank you, I'll ask over with the SwiftGodot group
